#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
    if ! getent group dwarf >/dev/null ; then
        groupadd -r dwarf
    fi

    if ! getent passwd dwarf >/dev/null ; then
        useradd -r -g dwarf -G dwarf,libvirt -d /var/lib/dwarf \
                -s /sbin/nologin dwarf
    fi

    mkdir -p /var/lib/dwarf/instances/_base
    mkdir -p /var/lib/dwarf/images

    chown -R dwarf:dwarf /var/lib/dwarf /etc/dwarf.conf

    chown root:root /etc/sudoers.d/dwarf
    chmod 440 /etc/sudoers.d/dwarf

    if ! [ -e /var/lib/dwarf/dwarf.db ] ; then
        su -s /bin/sh -c 'dwarf-manage db-init' dwarf
    fi
fi

#DEBHELPER#

exit 0
