#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then

    # Create the dwarf user
    if ! getent passwd dwarf >/dev/null ; then
	adduser \
	    --system \
	    --ingroup libvirtd \
	    --home /var/lib/dwarf \
	    --no-create-home \
	    --shell /bin/sh \
	    dwarf
    fi

    # Create the dwarf directories
    mkdir -p /var/lib/dwarf/instances/_base
    mkdir -p /var/lib/dwarf/images

    chown -R dwarf:root /var/lib/dwarf /etc/dwarf.conf
    chmod 600 /etc/dwarf.conf

    chown root:root /etc/sudoers.d/dwarf
    chmod 440 /etc/sudoers.d/dwarf

    # Initialize the database
    if [ ! -e /var/lib/dwarf/dwarf.db ] ; then
	su -c 'dwarf-manage db-init' dwarf
    fi
fi

#DEBHELPER#

exit 0
