#!/bin/bash -e
# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function usage()
{
    cat <<EOF
$@

Usage: $(basename $0) <target> [options]

Available targets:
$(for t in $(declare -F | awk '/ build_/ { print $3 }') ; do \
    target=${t#build_} ; \
    echo "   ${target}" ; \
done)
EOF

    exit 2
}

function build_tarball()
{
    [ -e build/${SRC_TGZ} ] && exit
    [ -e build/${SRC_DIR} ] && rm -r build/${SRC_DIR}
    mkdir -p build/${SRC_DIR}

    # Copy the source and build the orig tarball
    tar -cvf - bin dwarf etc setup.py README | tar -C build/${SRC_DIR} -xf -
    tar -C build -czvf build/${SRC_TGZ} ${SRC_DIR}
}

function build_release()
{
    local release=${1}
    local name=${2}

    [ -e build/${name} ] && rm -r build/${name}

    # Extract the orig tarball
    [ -e build/${SRC_DIR} ] && rm -r build/${SRC_DIR}
    tar -C build -xzvf build/${SRC_TGZ}

    # Rename the orig source dir
    mv build/${SRC_DIR} build/${name}

    # Overlay the debian files and fix the changelog
    tar -cvf - debian | tar -C build/${name} -xf -
    sed -s 's/RELEASE/'${release}'/g' changelog > \
        build/${name}/debian/changelog
}

[ $# -gt 0 ] || usage "Error: Missing target"

target=${1}
shift

[ "$(type -t build_${target})" = "function" ] || \
    usage "Error: Unknown target ${target}"

# Get the source version from setup.py
version=$(grep ' version=' setup.py | awk -F= '{print $2}' | tr -d "',")

# Names of the source tarball and directory
SRC_TGZ=dwarf_${version}.orig.tar.gz
SRC_DIR=dwarf-${version}

build_${target} "$@"
