#!/bin/bash

URL=http://127.0.0.1:8773/db

case "$1" in
    init)
	curl -X POST ${URL}
	;;

    dump)
	curl -X GET ${URL}
	echo
	curl -X GET ${URL}/servers
	curl -X GET ${URL}/keypairs
	curl -X GET ${URL}/images
	;;
    *)
	echo "Unknown command '$1'"
	exit 1
esac
