#!/bin/bash

URL=http://127.0.0.1:8773/db

case "$1" in

    init)
	curl -X POST ${URL}
	;;

    dump)
	curl -X GET ${URL}
	echo
	echo "servers"
	curl -X GET ${URL}/servers
	echo
	echo "images"
	curl -X GET ${URL}/images
	echo
	echo "keypairs"
	curl -X GET ${URL}/keypairs
	echo
	echo "flavors"
	curl -X GET ${URL}/flavors
	;;

    delete)
	curl -X DELETE ${URL}/${2}
	;;

    *)
	echo "Unknown command '$1'"
	exit 1

esac
