#!/usr/bin/env python
#
# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
# Copyright (c) 2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wrapper to handle expected pylint errors rather than turning them off
# completely

import re
import signal
import subprocess
import sys


def preexec_fn():
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)


e1101 = re.compile(r"Instance of '_Config' has no '[0-9a-zA-Z_]+' member")

sys.argv[0] = 'pylint'
proc = subprocess.Popen(sys.argv, stdout=subprocess.PIPE, close_fds=True,
                        shell=False, preexec_fn=preexec_fn)

retval = 0
header = None

while True:
    line = proc.stdout.readline()

    # Check for EOF
    if not line:
        break

    # Skip expected E1101 errors
    if e1101.search(line):
        continue

    # Grab the 'header'
    if line.startswith('************* Module'):
        header = line
        continue

    # We have a valid error if we came here
    retval = 1

    if header:
        sys.stdout.write(header)
        header = None
    sys.stdout.write(line)
    sys.stdout.flush()

sys.exit(retval)
